// <auto-generated />
using System;
using DAL.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(RedDbContext))]
    [Migration("20200330224136_updateSaleTable")]
    partial class updateSaleTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.Number", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsChoosen");

                    b.Property<bool?>("IsPrivate");

                    b.Property<string>("No");

                    b.Property<string>("UserId");

                    b.HasKey("ID");

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("DAL.Entities.Package", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("Units");

                    b.HasKey("ID");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("DAL.Entities.Sale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ActivationDate");

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("CustomerId");

                    b.Property<string>("CustomerName");

                    b.Property<string>("District");

                    b.Property<string>("Mobile1");

                    b.Property<string>("Mobile2");

                    b.Property<int?>("NumberId");

                    b.Property<int?>("PackageId");

                    b.Property<DateTime?>("RejectDate");

                    b.Property<long>("Serial");

                    b.Property<int?>("StatusId");

                    b.Property<string>("UserId");

                    b.Property<DateTime?>("VisitDate");

                    b.HasKey("ID");

                    b.HasIndex("NumberId");

                    b.HasIndex("PackageId");

                    b.HasIndex("StatusId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("DAL.Entities.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("DAL.Entities.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArabicName");

                    b.Property<string>("City");

                    b.Property<string>("EnglishName");

                    b.Property<string>("Mobile");

                    b.HasKey("ID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("DAL.Entities.Sale", b =>
                {
                    b.HasOne("DAL.Entities.Number", "Number")
                        .WithMany("Sales")
                        .HasForeignKey("NumberId");

                    b.HasOne("DAL.Entities.Package", "Package")
                        .WithMany("Sales")
                        .HasForeignKey("PackageId");

                    b.HasOne("DAL.Entities.Status", "Status")
                        .WithMany("Sales")
                        .HasForeignKey("StatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
